---
# play1
- name: add a user
  hosts: dc2
  tasks:
    - name: add user {{ username }}
      user:
        name: "{{ username }}"
        uid: 1234
        shell: /sbin/nologin

    - name: remove user {{ username }}
      user:
        name: "{{ username }}"
        state: absent
        remove: yes
